# Generated by Django 3.0 on 2023-03-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passports',
            new_name='Passport',
        ),
    ]
