# Generated by Django 3.0 on 2023-03-26 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersdata', '0002_auto_20230324_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('citizenship', models.CharField(max_length=50)),
                ('duration_of_stay_from', models.DateField(verbose_name='Duration OF Stay From')),
                ('duration_of_stay_to', models.DateField(verbose_name='Duration OF Stay To')),
                ('card_photo', models.ImageField(null=True, upload_to='passport/photo/% Y/% m/% d/', verbose_name='Passport Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
