# Generated by Django 3.0 on 2023-03-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersdata', '0003_migrationcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationcard',
            name='card_photo',
            field=models.ImageField(null=True, upload_to='migration_card/photo/% Y/% m/% d/', verbose_name='Passport Photo'),
        ),
    ]
