# Generated by Django 3.0 on 2023-03-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersdata', '0004_auto_20230326_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationcard',
            name='card_photo',
            field=models.ImageField(null=True, upload_to='migration_card/photo/% Y/% m/% d/', verbose_name='Migration Card Photo'),
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('date_of_issue', models.DateField(verbose_name='Date Of Issue')),
                ('patent_photo', models.ImageField(null=True, upload_to='patent_photo/photo/% Y/% m/% d/', verbose_name='Patent Photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
